version: "3"

services:
  db:
    image: postgres
    deploy:
      replicas: 1
      restart: always
    #command: bash -c "psql -U admin
    #    && CREATE TABLE public.persons (id int PRIMARY KEY, lastName varchar(255), firstName varchar(255))
    #  "
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
      