version: "3"

services:
  db:
    image: gabrielteotonio/postgres:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
  shiny:
    image: gabrielteotonio/shiny-db:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true 
        - traefik.docker.network=traefik-public 
        - traefik.constraint-label=traefik-public 
        - traefik.http.routers.euler.rule=Host(`app.gabrielteotonio.com`) 
        - traefik.http.routers.euler.entrypoints=http
        - traefik.http.middlewares.euler.redirectscheme.scheme=https 
        - traefik.http.middlewares.euler.redirectscheme.permanent=true 
        - traefik.http.routers.euler-secured.rule=Host(`app.gabrielteotonio.com`) 
        - traefik.http.routers.euler-secured.entrypoints=https
        - traefik.http.routers.euler-secured.tls.certresolver=le 
        - traefik.http.services.euler-secured.loadbalancer.server.port=3838 
    volumes:
      - ./srv/shinyapps:/srv/shiny-server
      - ./srv/shinylog:/var/log/shiny-server
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3838:3838
    networks:
      - backend
      - traefik-public
  traefik:
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-public-http.rule=Host(`traefik.sys.app.gabrielteotonio.com`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        - traefik.http.routers.traefik-public-https.rule=Host(`traefik.sys.app.gabrielteotonio.com`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=contact@gabrielteotonio.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-public

volumes:
  traefik-public-certificates:

networks:
  backend:
  traefik-public: