version: "3"

services:
  db:
    image: postgres
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      