version: "3"

services:
  db:
    image: gabrielteotonio/postgres:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
      