version: "3"

services:
  db:
    image: gabrielteotonio/postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      